# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "centos-64-x64-vbox4210-nocm"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210-nocm.box"

  # Vagrant is able to define and control multiple guest machines per Vagrantfile. This is 
  # known as a "multi-machine" environment.

  # db server
  config.vm.define "db" do |db|
    db.vm.hostname = "db-msn-1.custapps.net"
    db.vm.network :forwarded_port, guest: 5432, host: 5432
    db.vm.network :private_network, ip: "192.168.33.10"
    db.vm.provision :ansible do |ansible|
      ansible.playbook = "dbservers.yml"
      ansible.inventory_path = "vagrant/hosts.ini"
      ansible.verbose = true
      ansible.sudo = true
    end
  end
  
  # web services server
  config.vm.define "ws" do |ws|
    ws.vm.hostname = "ws-msn-1.custapps.net"
    ws.vm.network :forwarded_port, guest: 42100, host: 42100
    ws.vm.network :private_network, ip: "192.168.33.20"
    ws.vm.provision :ansible do |ansible|
      ansible.playbook = "wsservers.yml"
      ansible.inventory_path = "vagrant/hosts.ini"
      ansible.verbose = true
      ansible.sudo = true
    end
  end
 
  # portal server
  config.vm.define "portal" do |portal|
    portal.vm.hostname = "portal-msn-1.custapps.net"
    portal.vm.network :forwarded_port, guest: 62100, host: 62100
    portal.vm.network :private_network, ip: "192.168.33.30"
    portal.vm.provision :ansible do |ansible|
      ansible.playbook = "portalservers.yml"
      ansible.inventory_path = "vagrant/hosts.ini"
      ansible.verbose = true
      ansible.sudo = true
    end
  end

end
